### ISSUE TITLE
Missing BuildConfig.java in SbpPaymentsAndroid repository

### ISSUE THREAD

**Issue by KmnPetr** [MrOlolo/SbpPaymentsAndroid#1]
Hello, @MrOlolo!
Currently, I'm solving the issue of connecting SBP in the Android application and found your repository SbpPaymentsAndroid.
However, your version lacks the necessary file BuildConfig.java.
Based on the code, it's clear that this class should contain at least 2 fields: "NSPK_URL" and "scheme".
Could you please advise where I can find the values for these two fields? Or if this class doesn't contain confidential information, could you provide the code for this BuildConfig.java class?

**Comment by MrOlolo** [comment]
Hello! This file generates at gradle build. You can build project to check it or watch at gradle script. 
`NSPK_URL = "https://qr.nspk.ru/"`
